import Vue from "vue";
import Unicon from "vue-unicons/dist/vue-unicons-vue2.umd";

import {
  uniTimes,
  uniArrowCircleLeft,
  uniArrowFromRight,
  uniMessage,
  uniCog,
  uniHardHat,
  uniInfoCircle,
  uniLayerGroupMonochrome,
  uniCarWash,
  uniArrowCircleRight,
  uniSearch,
  uniSearchAlt,
  uniShoppingCart,
  uniBuilding,
  uniPhoneAlt,
  uniPhone,
  uniMapMarker,
  uniShoppingCartAlt,
  uniFacebookF,
  uniInstagram,
  uniTwitter,
  uniLinkedin,
  uniArrowLeft,
  uniHome,
} from "vue-unicons/dist/icons";

Unicon.add([
  uniArrowLeft,
  uniTimes,
  uniArrowCircleLeft,
  uniArrowFromRight,
  uniMessage,
  uniHome,
  uniCog,
  uniHardHat,
  uniInfoCircle,
  uniFacebookF,
  uniInstagram,
  uniTwitter,
  uniLinkedin,
  uniArrowCircleRight,
  uniMapMarker,
  uniPhoneAlt,
  uniPhone,
  uniBuilding,
  uniLayerGroupMonochrome,
  uniCarWash,
  uniSearch,
  uniSearchAlt,
  uniShoppingCart,
  uniShoppingCartAlt,
]);
Vue.use(Unicon);
